language: java
jdk:
  - oraclejdk8
 
before_install:
 - chmod +x gradlew

install: ./gradlew checkSnapshotDependencies compileJava
script: ./gradlew eclipse build jacocoTestReport javadoc checkSnapshotDependencies

after_failure:
- cat build/test-results/*.xml
