dist: bionic
language: java
jdk:
  - openjdk8
  - openjdk11

before_install:
 - chmod +x gradlew gradle/wrapper/gradle-wrapper.jar

install: ./gradlew checkSnapshotDependencies compileJava
script: ./gradlew check jacocoTestReport javadoc javadocJar sourcesJar checkSnapshotDependencies

after_failure:
- cat build/test-results/test/*.xml
